### ISSUE TITLE
mongodb fails to start: unrecognised option '--break-mongo'

### ISSUE THREAD

**Issue by funkenstrahlen** [yongjhih/docker-parse-server#11]
I used the docker compose to build. MongoDB fails to start:

```
Attaching to root_mongo-data_1, root_mongo_1, root_parse-cloud-code_1, root_parse-server_1
mongo-data_1       | Error parsing command line: unrecognised option '--break-mongo'
mongo-data_1       | try 'mongod --help' for more information
root_mongo-data_1 exited with code 2
```

**Comment by funkenstrahlen** [comment]
I assume this is wanted? https://github.com/docker/compose/issues/942

**Comment by yongjhih** [comment]
Yes.

mongo-data is a volume cotainer, so i make it break.

ref. http://www.diogogmt.com/running-mongodb-with-docker-and-compose/

**Comment by funkenstrahlen** [comment]
Ok got it. You can close this.

Maybe you can add a little comment into the docker compose file.

**Comment by micheljung** [comment]
So this is intended? Because it also seems to crash "cloud-code":

```
mongo-data_1        | Error parsing command line: unrecognised option '--break-mongo'
mongo-data_1        | try 'mongod --help' for more information
parse-cloud-code_1  | hello.js
parse-cloud-code_1  | main.js
parse-cloud-code_1  | twitch.js
fortuna_mongo-data_1 exited with code 2
fortuna_parse-cloud-code_1 exited with code 0
```

**Comment by yongjhih** [comment]
Yes, mongo-data and parse-cloud-code are as volume container, so they would be exited that's intended.
