### ISSUE TITLE
Facebook App ID

### ISSUE THREAD

**Issue by alombard** [yongjhih/docker-parse-server#12]
Not sure if I missed this but would it be possible to add the Facebook App ID to your environmental variables for this image?

**Comment by yongjhih** [comment]
Yes, it would by the following command:

```sh
$ docker run -d                        \
             -e FACEBOOK_APP_IDS={fbAppId1,fbAppId2}
             -e APP_ID={appId}         \
             -e MASTER_KEY={masterKey} \
             -p 1337:1337              \
             -p 2022:22                \
             --link mongo              \
             --name parse-server       \
             yongjhih/parse-server
```

**Comment by alombard** [comment]
Perfect - I'll give that a try.  Thanks.

**Comment by yongjhih** [comment]
BTW, you could see more environmental variables in https://github.com/yongjhih/docker-parse-server/blob/master/docker-compose.yml .

**Comment by alombard** [comment]
Thanks again.  Perhaps this could be added to the ReadMe - it wasn’t clear to me in your samples without looking inside the Docker / Docker-Compose files themselves. 



On March 7, 2016 at 1:59:31 PM, Andrew Chen (notifications@github.com) wrote:

BTW, you could see more environmental variables in https://github.com/yongjhih/docker-parse-server/blob/master/docker-compose.yml .
