### ISSUE TITLE
Can't connect to parse server (hostname: localhost) 

### ISSUE THREAD

**Issue by jacek-berlin** [yongjhih/docker-parse-server#23]
Hello, 
I used the docker setup (compose). 
all containers are running on a remote server. 
I can see the dashboard in my browser . Dashboard is making requests to the server which cannot be contacted, it tries to connect to http://localhost:1337/parse. 
Dashboard(my browser) sends requests to localhost where locahost is my laptop, not server where docker containers are running. 
Is there any intended way to make it running over the internet where Dashboard is called in Browser which does not run on the same machine as docker containers? 

thank you

**Comment by yongjhih** [comment]
`SERVER_URL=http://<PUBLIC_IP>:1337/parse APP_ID=myAppId MASTER_KEY=myMasterKey docker-compose up -d`

**Comment by jacek-berlin** [comment]
Thanks, I changed the SERVER_URL in docker-compose and placed separate vhosts for dashboard and server.

**Comment by arielelkin** [comment]
Please update the documentation, otherwise the docker-compose file only works for `localhost`.

**Comment by yongjhih** [comment]
More info for parse-dashboard: https://github.com/yongjhih/docker-parse-dashboard

**Comment by yongjhih** [comment]
I've added a chapter about letsencrypt: https://github.com/yongjhih/docker-parse-server#usage-of-letsencrypt-for-parse-dashboard

**Comment by yongjhih** [comment]
### Usage of standalone parse dashboard

Up containers without parse-dashboard:

```sh
$ APP_ID=myAppId MASTER_KEY=myMasterKey docker-compose up -d parse-server parse-cloud-code mongo mongo-data
```

Up standalone parse-dashboard: https://github.com/yongjhih/docker-parse-dashboard
