### ISSUE TITLE
Dashboard with docker-compose still loading

### ISSUE THREAD

**Issue by Thomas-Giacomelli** [yongjhih/docker-parse-server#24]
I use your lastest build of parse-server, with the correction of the issue #22 of the Dashboard.

I use a LetsEncrypt SSL certificate to access via https to the Dashboard (because http is not accessible), and I saw indefinitly the Dashboard loading like this image :

[http://goo.gl/UTjcWg](url)

I remove the `-d` option of docker-compose command line, that's the log I have :

> parse-cloud-code_1 | hello.js
> parse-cloud-code_1 | main.js
> parse-cloud-code_1 | twitch.js
> mongo-data_1       | Error parsing command line: unrecognised option '--break-mongo'
> mongo-data_1       | try 'mongod --help' for more information
> parse-server_1     | npm info it worked if it ends with ok
> parse-server_1     | npm info using npm@3.8.3
> dockerparse2_mongo-data_1 exited with code 2
> dockerparse2_parse-cloud-code_1 exited with code 0
> parse-server_1     | npm info using node@v5.10.0
> parse-server_1     | npm info lifecycle parse-server-example@1.2.0~prestart: parse-server-example@1.2.0
> parse-server_1     | npm info lifecycle parse-server-example@1.2.0~start: parse-server-example@1.2.0
> parse-server_1     |
> parse-server_1     | > parse-server-example@1.2.0 start /parse
> parse-server_1     | > nodemon --watch /parse/cloud index.js
> parse-server_1     |
> parse-dashboard_1  | npm info it worked if it ends with ok
> parse-dashboard_1  | npm info using npm@3.8.3
> parse-dashboard_1  | npm info using node@v5.10.0
> parse-dashboard_1  | npm info lifecycle parse-dashboard@1.0.6~predashboard: parse-dashboard@1.0.6
> parse-dashboard_1  | npm info lifecycle parse-dashboard@1.0.6~dashboard: parse-dashboard@1.0.6
> parse-dashboard_1  |
> parse-dashboard_1  | > parse-dashboard@1.0.6 dashboard /parse-dashboard
> parse-dashboard_1  | > node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch
> parse-dashboard_1  |
> parse-server_1     | [nodemon] 1.9.1
> parse-server_1     | [nodemon] to restart at any time, enter `rs`
> parse-server_1     | [nodemon] watching: /parse/cloud/**/*
> parse-server_1     | [nodemon] starting `node index.js`
> parse-dashboard_1  | The dashboard is now available at http://localhost:4040/
> parse-server_1     | parse-server-example running on http://localhost:1337/parse (:1337/parse)                                                      57% 54/68 build modulesContainer#eachAtRule is deprecated. Use Container#walkAtRules instead.
> parse-dashboard_1  | Container#eachRule is deprecated. Use Container#walkRules instead.
> parse-dashboard_1  | Container#eachDecl is deprecated. Use Container#walkDecls instead.
> parse-dashboard_1  | Node#removeSelf is deprecated. Use Node#remove.         31% 82/231 build modulesNode#before is deprecated. Use NHash: 85303ea680e020d55d40 parse-dashboard_1  | Version: webpack 1.12.14
> parse-dashboard_1  | Time: 136083ms
> parse-dashboard_1  |                                    Asset     Size  Chunks             Chunk Names
> parse-dashboard_1  | img/cf0a48bbd61302f119a4576be8e01ed9.png   652 kB          [emitted]
> parse-dashboard_1  |                      dashboard.bundle.js  3.55 MB       0  [emitted]  dashboard
> parse-dashboard_1  |                              sprites.svg  99.3 kB          [emitted]
> parse-dashboard_1  |     + 1243 hidden modules
>

**Comment by yongjhih** [comment]
I've reproduced. If you access dashboard from remote not localhost, you must access with basic auth via https only by the following command:

```sh
USER1=yongjhih \ # your username
USER1_PASSWORD=yongjhih \ # your password
APP_ID=myAppId MASTER_KEY=myMasterKey docker-compose up
```

ref. https://github.com/yongjhih/docker-parse-server#usage-of-letsencrypt-for-parse-dashboard

And I found browser blocked some scripts, click unblock it.

**Comment by Thomas-Giacomelli** [comment]
Thanks for your reply ! 

It don't work for me, I try with docker-compose-le.yml and it don't launch.

I deal with a http access, it works, great job !

**Comment by yongjhih** [comment]
You can update images by the following commands:

```sh
docker pull yongjhih/parse-server
docker pull yongjhih/parse-dashbard
```

And try again: https://github.com/yongjhih/docker-parse-server#usage-of-https-certificated-domain-with-letsencrypt
