### ISSUE TITLE
How to scale this?

### ISSUE THREAD

**Issue by katopz** [yongjhih/docker-parse-server#29]
![Parse Server Diagram](https://github.com/yongjhih/docker-parse-server/raw/master/art/parse-server-diagram.png)
Maybe sharding Mongo? HAProxy? I'm kinda new to this and just try to make sure that I can scale it later.
So any idea or guides is welcome.

Thanks

**Comment by yongjhih** [comment]
Deploy sharded mongo cluster:
https://docs.mongodb.org/manual/tutorial/deploy-shard-cluster/

Then, run parse-server with sharded mongo cluster:

```sh
$ docker run -d \
             -e DATABASE_URI=mongodb://shard.mongodb.intra:27017/ \
             -e APP_ID=${PARSE_APP_ID}                            \
             -e MASTER_KEY=${PARSE_MASTER_KEY}                    \
             -p 1337:1337                                        \
             -p 2022:22                                          \
             --name parse-server                                 \
             yongjhih/parse-server
```

**Comment by katopz** [comment]
Cool thanks, I'll try.

**Comment by freeznet** [comment]
following on this, how to scale the parse-server, if i using `docker-compose scale parse-server=4`, i get error since cannot bind on the same host port.
