### ISSUE TITLE
Missing parse-cloud-code-git in docker compose?

### ISSUE THREAD

**Issue by katopz** [yongjhih/docker-parse-server#31]
Refer from readme If I use...
> or with docker-compose:

I think `parse-cloud-code-git` is never create?
And that will cause...
```
$ docker exec -i parse-cloud-code-git ssh-add-key < ~/.ssh/id_rsa.pub
Error response from daemon: No such container: parse-cloud-code-git
```
And I assume from
```
Starting katopz_parse-cloud-code_1
Starting katopz_mongo-data_1
katopz_mongo_1 is up-to-date
Recreating katopz_parse-server_1
Recreating katopz_parse-dashboard_1
Recreating katopz_git_1
```
Judge from port `2022` it should be `katopz_git_1` so I try...
```
$ docker exec -i katopz_git_1 ssh-add-key < ~/.ssh/id_rsa.pub
$ git clone ssh://git@localhost:2022/katopz_git_1
Cloning into 'katopz_git_1'...
ssh: connect to host localhost port 2022: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Any hint?

Thanks

**Comment by katopz** [comment]
Gotcha, for some reason my mac use this ip instead `192.168.99.100` of `locahost`
And `REPO_PATH` it's not `katopz_git_1` but `parse-cloud-code` so here we go.
```
$ git clone ssh://git@192.168.99.100:2022/parse-cloud-code
Cloning into 'parse-cloud-code'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
```
BTW, Would be nice if `docker-compose` name is match or somehow note in `README`.

Cheers

**Comment by yongjhih** [comment]
If you use docker-compose.yml, the git container name will be decorated such as `katopz_git_1`

So add ssh key into git container of syntax is:

```sh
$ docker exec -i ${git_container} ssh-add-key < ~/.ssh/id_rsa.pub
```

And git container binds 2022 port by docker-compose.yml configured, so you could clone parse-cloud-code repo by the following command:

```sh
git clone ssh://git@localhost:2022/parse-cloud-code
```
