### ISSUE TITLE
PM2 integration?

### ISSUE THREAD

**Issue by katopz** [yongjhih/docker-parse-server#35]
Refer to https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04

Seem like I need PM2 there. The question is, Is PM2 suppose to run inside or outside docker?
And should it install with docker compose or manually do it?
Or maybe PM2 job alike already done somewhere so I am no need PM2 here?

Thanks

**Comment by yongjhih** [comment]
PM2 is a loading balancer for node service cluster. I think it's not necessary.

About node process manager alternatives for example:

```sh
// normal
$ node index.js
```

```sh
// pm2 as worker for loading balance
$ pm2 index.js
```

```sh
// forever for monitor
$ forever index.js
```

```sh
// nodemon for monitor
$ nodemon index.js
```

**Comment by katopz** [comment]
Thanks! I've a lot to learn here. ^^

**Comment by Sadmansamee** [comment]
How did you use pm2 with docker? enlight me please. @katopz

**Comment by samwize** [comment]
@Sadmansamee A few changes to Dockfile should get pm2 to run. Read http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/
