### ISSUE TITLE
Why this image not starting automatically?

### ISSUE THREAD

**Issue by egorvas** [yongjhih/docker-parse-server#4]
Hi, Im trying to start your docker image, but its not started. Thats example of my commands:

`docker run -d -p 27017:27017 --name mongo mongo`
`docker run -d -e APP_ID=myappid -e MASTER_KEY=myapppassword -p 1337:1337 --link mongo yongjhih/parse-server`

But after that server is not started. And in docker ps -a I see something like that:

`6848bbf60604        yongjhih/parse-server    "node"  13 seconds ago      Exited (0) 12 seconds ago   berserk_kowalevski`
Where is my error?

**Comment by yongjhih** [comment]
Try to pull yongjhih/parse-server image by the following command before `docker run -d`:

```sh
docker pull yongjhih/parse-server
```

**Comment by egorvas** [comment]
Yeah, thank you, pull is helped.
