### ISSUE TITLE
docker-compose -f docker-compose-le.yml up fail if run twice

### ISSUE THREAD

**Issue by cleever** [yongjhih/docker-parse-server#41]
If I run 
`docker-compose -f docker-compose-le.yml up`

the first time runs ok.

But if I need to run again, this error occurs:

`nginx                                | 2016/05/12 03:26:09 [emerg] 1#1: open() "/etc/nginx/vhost.d/default" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:56
nginx                                | nginx: [emerg] open() "/etc/nginx/vhost.d/default" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:56
`

And https stops working.

So it's need to delete all containers do work again

with:

`docker rm -f $(docker ps -a -q)`

**Comment by yongjhih** [comment]
```sh
docker-compose -f docker-compose-le.yml down && docker-compose -f docker-compose-le.yml up
```
or
```
docker-compose -f docker-compose-le.yml restart
```

**Comment by cleever** [comment]
Will restart command read all modified configuration and reconfigure containers and settings?

**Comment by yongjhih** [comment]
Should be
