### ISSUE TITLE
PARSE_DASHBOARD_SERVER_URL not get value from params

### ISSUE THREAD

**Issue by katopz** [yongjhih/docker-parse-server#42]
refer to https://github.com/yongjhih/docker-parse-server/blob/master/docker-compose.yml#L113
I think it should be 
```
PARSE_DASHBOARD_SERVER_URL = $PARSE_DASHBOARD_SERVER_URL
```
so it can set from external params, or maybe I miss something here?

**Comment by katopz** [comment]
Also https://github.com/yongjhih/docker-parse-dashboard/blob/master/docker-compose.yml#L13
should except it too
```
PARSE_DASHBOARD_SERVER_URL: $PARSE_DASHBOARD_SERVER_URL
```

**Comment by yongjhih** [comment]
The parse-dashboard did not have a default value for serverUrl, so you can not ignore SERVER_URL anymore while docker-compose starting:

```sh
SERVER_URL=xxx MASTER_KEY=mmm APP_ID=aaa docker-compose up
```

And PARSE_DASHBOARD_SERVER_URL is docker inner env var for parse-dashboard program, I design a global/unique var naming SERVER_URL for docker stack.
