### ISSUE TITLE
Usage with docker-machine

### ISSUE THREAD

**Issue by gerhardsletten** [yongjhih/docker-parse-server#6]
On a mac I had to specify the DATABASE_URI with ip:port to my mongodb docker to make in work:

```shell
docker run -d -p 27017:27017 --name mongo mongo
docker run -e APP_ID=secret -e DATABASE_URI=mongodb://192.168.99.100:27017/dev -e MASTER_KEY=super-secret -p 1337:1337 yongjhih/parse-server
```

**Comment by yongjhih** [comment]
I'll reproduce it on mac later. Thanks for your report.

**Comment by gerhardsletten** [comment]
Don't know it there is something special on my machine (OS X 10.10.5) or using docker links with docker-machine, but in order to use --link parameter, the linked docker will not be available on 172.0.0.1 so I need to find the ip-adresse like this:

```javascript
...
var links = require('docker-links').parseLinks(process.env);
...
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://' + links.mongo.hostname + ':27017/dev',
  ...
});
```

Should I push a pull request for it?

**Comment by yongjhih** [comment]
I dont not sure, but you can make it. I'll merge it if nobody has another opinion.

**Comment by yongjhih** [comment]
#7 merged
