### ISSUE TITLE
2.2.22 is out!

### ISSUE THREAD

**Issue by andrew8712** [yongjhih/docker-parse-server#66]
Can you please update package.json and release a new version?

**Comment by andrew8712** [comment]
I see package.json updated, thanks! How about pushing a new tag?

**Comment by andrew8712** [comment]
Hi @yongjhih any timeline on this? `docker-compose up` still runs 2.2.19

**Comment by yongjhih** [comment]
https://github.com/yongjhih/docker-parse-server/releases/tag/2.2.22
