### ISSUE TITLE
why did you stop using tags at docker-hub?

### ISSUE THREAD

**Issue by derDieDasJojo** [yongjhih/docker-parse-server#87]
until 4 months ago you pushed every image with a tag.
https://hub.docker.com/r/yongjhih/parse-server/tags/

if you continue doing so, we could use continue using your awesome image - wich would be great.

best regards
jojo

**Comment by yongjhih** [comment]
@derDieDasJojo , thanks for giving the notice that I forgot to push tags for it. I have already pushed tags and now it auto build these images.

**Comment by derDieDasJojo** [comment]
wow! thanks a lot for your super fast response.
close

**Comment by derDieDasJojo** [comment]
thank you very much for your super fast response :)

**Comment by derDieDasJojo** [comment]
closed
