### ISSUE TITLE
Parse Android issue

### ISSUE THREAD

**Issue by pulse1989** [yongjhih/docker-parse-server#9]
Hi

Thanks for the awesome docker image. Recently i posted an issue i was having with parse in general on the parseServer page and i got this response yesterday where they said the issue was fixed... 

https://github.com/ParsePlatform/parse-server/issues/413

the issue was later advised to be resolved with this git commit... 

https://github.com/ParsePlatform/parse-server/pull/679

I've pulled the latest docker image from here and tested but i am still getting error 403 forbidden... not sure if you have updated to the latest push since the issue resolved?

Thanks man!

**Comment by yongjhih** [comment]
Maybe parse-server module did not been uploaded or parse-server docker image did not built with latest parse-server module.

I'm going to trigger hub.docker.com to rebuild parse-server image. You may wait for a while.

Refer these:

* https://hub.docker.com/r/yongjhih/parse-server/builds/
* https://www.npmjs.com/package/parse-server

**Comment by yongjhih** [comment]
I'm going to build a dev image based on github master instead of npm.

**Comment by pulse1989** [comment]
Thanks man. i will wait :)

**Comment by yongjhih** [comment]
I have added dev image, this is first build:
https://hub.docker.com/r/yongjhih/parse-server/builds/bwgohde8hfam4u64s8ml8pc/
